services:
  mysql:
    image: mysql:8.0
    container_name: bank_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bank_db
      MYSQL_USER: bankuser
      MYSQL_PASSWORD: bankpassword
    ports:
      - "3306:3306"
    volumes:
      - bank_mysql_data:/var/lib/mysql

volumes:
  bank_mysql_data:
